ERROR - 2024-09-19 00:50:45 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2024-09-19 00:50:45 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp2\htdocs\cafe-PUM\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp2\htdocs\cafe-PUM\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp2\htdocs\cafe-PUM\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp2\htdocs\cafe-PUM\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp2\htdocs\cafe-PUM\app\Controllers\Dashboard.php(24): CodeIgniter\BaseModel->findAll()
#5 C:\xampp2\htdocs\cafe-PUM\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#6 C:\xampp2\htdocs\cafe-PUM\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#7 C:\xampp2\htdocs\cafe-PUM\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\cafe-PUM\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-09-19 00:50:45 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp2\htdocs\cafe-PUM\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp2\\htdoc...', 96, Array)
#1 C:\xampp2\htdocs\cafe-PUM\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Dashboard), true)
#2 C:\xampp2\htdocs\cafe-PUM\system\Debug\Exceptions.php(229): include('C:\\xampp2\\htdoc...')
#3 C:\xampp2\htdocs\cafe-PUM\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp2\htdocs\cafe-PUM\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2024-09-19 00:50:51 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2024-09-19 00:50:51 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp2\htdocs\cafe-PUM\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp2\htdocs\cafe-PUM\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp2\htdocs\cafe-PUM\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp2\htdocs\cafe-PUM\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp2\htdocs\cafe-PUM\app\Controllers\Dashboard.php(24): CodeIgniter\BaseModel->findAll()
#5 C:\xampp2\htdocs\cafe-PUM\system\CodeIgniter.php(824): App\Controllers\Dashboard->index()
#6 C:\xampp2\htdocs\cafe-PUM\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#7 C:\xampp2\htdocs\cafe-PUM\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\cafe-PUM\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-09-19 00:50:51 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp2\htdocs\cafe-PUM\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp2\\htdoc...', 96, Array)
#1 C:\xampp2\htdocs\cafe-PUM\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Dashboard), true)
#2 C:\xampp2\htdocs\cafe-PUM\system\Debug\Exceptions.php(229): include('C:\\xampp2\\htdoc...')
#3 C:\xampp2\htdocs\cafe-PUM\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp2\htdocs\cafe-PUM\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
